### ISSUE TITLE
Nice work! I'm trying to use this to map my runs. What is the LICENSE for this repo?

### ISSUE THREAD

**Issue by davidbradway** [andhint/everysinglestreet#9]

**Comment by andhint** [comment]
@davidbradway Just added an MIT license to the project. Also, I might be adding some scripts around pulling gpx files and maybe some viz stuff in the coming months if that's something you're interested in. Enjoy!

**Comment by davidbradway** [comment]
I'd love to see what else you have. Hope the biking project went well. Here's what I've been up to https://citystrides.com/users/11960/cities/171335

**Comment by davidbradway** [comment]
https://davidbradway.github.io/everystreetdurham/

**Comment by andhint** [comment]
Awesome! Looks like you're almost finished. Also, it looks like we might be pushing the limits of how much data should be charted 😅
